### ISSUE TITLE
Youtube link to lesson 3 (basic level)

### ISSUE THREAD

**Issue by harlock74** [alanswx/Tutorials_MiSTer#2]
Hi there,

First of all, many thanks for this very helpful tutorial and also for your continous and very much appreciated efforts on the Mister Arcade Cores.

When you get a chance would you mind checking he youtube link to lesson 3 of the Basic Tutorial? Reason being when I click on it I get redirected to lesson 2.

Many thanks and keep up with the great work!

Kind regards,

Alberto

**Comment by alanswx** [comment]
I haven’t finished level 3 yet.

**Comment by harlock74** [comment]
Hi Alan,

I see, many thanks for coming back to me.

Kind regards,

Alberto
